import {
  AppsRegular,
  ArrowMaximizeRegular,
  ArrowMinimizeRegular,
  ArrowMoveRegular,
  BatteryChargeRegular,
  BorderNoneRegular,
  BracesVariableRegular,
  ColorRegular,
  CursorRegular,
  DesktopPulseRegular,
  EyeRegular,
  FlowRegular,
  GaugeRegular,
  GridRegular,
  GlobeRegular,
  KeyboardRegular,
  KeyCommandRegular,
  MoreHorizontalRegular,
  PinRegular,
  RenameRegular,
  RulerRegular,
  SquareHintRegular,
  TextExpandRegular,
  TextFontRegular,
  TvRegular,
  WeatherMoonRegular,
  WindowMultipleRegular,
} from "@fluentui/react-icons";

const ICONS: Record<string, JSX.Element> = {
  Pin: <PinRegular />,
  WeatherMoon: <WeatherMoonRegular />,
  TextFont: <TextFontRegular />,
  Color: <ColorRegular />,
  Ruler: <RulerRegular />,
  BatteryCharge: <BatteryChargeRegular />,
  Tv: <TvRegular />,
  DesktopPulse: <DesktopPulseRegular />,
  ArrowMove: <ArrowMoveRegular />,
  WindowMultiple: <WindowMultipleRegular />,
  Grid: <GridRegular />,
  SquareHint: <SquareHintRegular />,
  ArrowMinimize: <ArrowMinimizeRegular />,
  BorderNone: <BorderNoneRegular />,
  Gauge: <GaugeRegular />,
  ArrowMaximize: <ArrowMaximizeRegular />,
  Keyboard: <KeyboardRegular />,
  Cursor: <CursorRegular />,
  KeyCommand: <KeyCommandRegular />,
  TextExpand: <TextExpandRegular />,
  Rename: <RenameRegular />,
  Eye: <EyeRegular />,
  MoreHorizontal: <MoreHorizontalRegular />,
  BracesVariable: <BracesVariableRegular />,
  Globe: <GlobeRegular />,
  Flow: <FlowRegular />,
};

export function ModuleIcon({ name }: { name: string }) {
  return <>{ICONS[name] ?? <AppsRegular />}</>;
}
